apiVersion: v1
kind: PersistentVolume
metadata:
 name: mongo-pv-volume
 namespace: sock-shop
 labels:
   app: carts-db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 10Gi
